version: 2.1

jobs:
  hello:
    docker:
      - image: circleci/buildpack-deps:latest
    parameters:
      bool_value:
        type: boolean
        default: true
    steps:
      - run:
          name: print hello
          command: |
            export bool_value=<< parameters.bool_value >>
            echo "bool_value is ${bool_value}"

workflows:
  hello:
    jobs:
      - hello
